package run.halo.app.service;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.lang.NonNull;
import run.halo.app.model.dto.DouYinDTO;
import run.halo.app.model.dto.WechatAccDTO;
import run.halo.app.model.dto.WeixinAppletDTO;
import run.halo.app.model.dto.ZhiHuDTO;


public interface AutoGeneratedContentService {


    @NonNull
    Page<WechatAccDTO> findAllWechatAccByRank(@NonNull Pageable pageable);

    @NonNull
    Page<WeixinAppletDTO> findAllWeixinAppletByRank(@NonNull Pageable pageable);

    @NonNull
    Page<ZhiHuDTO> findAllZhiHuByLike(@NonNull Pageable pageable);

    @NonNull
    Page<DouYinDTO> findAllDouYinByLike_count(@NonNull Pageable pageable);

}
